# This is a basic workflow to help you get started with Actions

name: CI
permissions:
  contents: write
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: wget https://github.com/swaggyP36000/TrollStore-IPAs/raw/main/apps_esign.json

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import json
    
            ipas = [
                'InstaRocketBH',
                'uYouEnhanced',
                'RedditPlus',
                'MobileTSS',
                'CarTube',
                'AppStorePlusPlus',
                'BHX',
                'CarPlex',
                'iTorrent',
            ]
    
            source_data = {
                "name": "a1ex IPA Library",
                "identifier": "com.a1ex.ipalibrary",
                "sourceURL": "https://raw.githubusercontent.com/swaggyP36000/TrollStore-IPAs/main/apps.json",
                "apps": []
            }
    
            with open('apps_esign.json', 'r') as f:
                original_data = json.load(f)
    
            filtered_ipas = [i for i in original_data['apps'] if i['name'] in ipas]
            source_data['apps'] = filtered_ipas
    
            with open('source.json', 'w+') as f:
                json.dump(source_data, f, indent=4)

      - name: Commit
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add source.json
          git commit -am "update"
          git push
